### ISSUE TITLE
Unhandled Exception in UserRepository.info

### ISSUE THREAD

**Issue by PellegrinoDurante** [Nerixyz/instagram_private_api#5]
Calling UserRepository.info() passing logged user's pk field thows this exception:
```
E/flutter (20005): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: type 'String' is not a subtype of type 'int' in type cast
E/flutter (20005): #0      _$UsersInfoResponseUserNametagFromJson (package:instagram_private_api/src/responses/users/info_response.g.dart:68:35)
E/flutter (20005): #1      new UsersInfoResponseUserNametag.fromJson (package:instagram_private_api/src/responses/users/info_response.dart:46:78)
E/flutter (20005): #2      _$UsersInfoResponseUserFromJson (package:instagram_private_api/src/responses/users/info_response.g.dart:158:40)
E/flutter (20005): #3      new UsersInfoResponseUser.fromJson (package:instagram_private_api/src/responses/users/info_response.dart:116:71)
E/flutter (20005): #4      _$UsersInfoResponseFromJson (package:instagram_private_api/src/responses/users/info_response.g.dart:13:33)
E/flutter (20005): #5      new UsersInfoResponse.fromJson (package:instagram_private_api/src/responses/users/info_response.dart:8:67)
E/flutter (20005): #6      UsersRepository.info (package:instagram_private_api/src/repositories/users_repository.dart:16:25)
```

and it is about `json['gradient'] as int`.

**Comment by Nerixyz** [comment]
I haven't updated this library in a long time, so there will be a lot of issues. You can change this in your open PR-draft. 

I'm generally not really happy with the json handling. Maybe there should be a better way of abstraction.
